[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "postgresql"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
PORT = "3000"
