[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci", "cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
PORT = "3000"
