name: aichatbot-platform
region: fra1

services:
  # Backend API Service (Python) - ONLY SERVICE
  - name: backend
    source_dir: /backend
    github:
      repo: axiestudio/aichatbot
      branch: main
      deploy_on_push: true

    # Force Python environment detection
    environment_slug: python

    # Force Python buildpack (critical for proper detection)
    buildpacks:
      - heroku/python

    build_command: pip install -r requirements.txt
    run_command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT

    instance_count: 1
    instance_size_slug: professional-xs  # 1GB RAM, 1 vCPU

    http_port: 8000

    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 120
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5

    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: SECRET_KEY
        value: "your-super-secret-key-change-in-production-minimum-32-characters"
        type: SECRET
      - key: ADMIN_USERNAME
        value: "stefan@axiestudio.se"
      - key: ADMIN_PASSWORD
        value: "STEfanjohn!12"
        type: SECRET
      - key: DATABASE_URL
        value: "postgresql://postgres.ompjkiiabyuegytncbwq:STEfanjohn!12@aws-0-eu-north-1.pooler.supabase.com:6543/postgres"
        type: SECRET
      - key: SUPABASE_URL
        value: "https://ompjkiiabyuegytncbwq.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcGpraWlhYnl1ZWd5dG5jYndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDg2MjYsImV4cCI6MjA2ODQyNDYyNn0.z9j2pwMfKjfR9Fs__fHkzwj9fjgiNOUQZ5Z9zv5FD6Q"
        type: SECRET

# Frontend temporarily disabled - focus on backend first
# Uncomment when backend is working:
#  - name: frontend
#    source_dir: /frontend
#    github:
#      repo: axiestudio/aichatbot
#      branch: main
#      deploy_on_push: true
#    buildpacks:
#      - heroku/nodejs
#    build_command: npm install && npm run build
#    instance_count: 1
#    instance_size_slug: basic-xxs
#    static_sites:
#      - name: frontend-static
#        source_dir: dist
#        index_document: index.html
#        error_document: index.html
#        catchall_document: index.html
#    envs:
#      - key: NODE_ENV
#        value: production

# Database temporarily disabled - using Supabase
# Uncomment when needed:
# databases:
#   - name: chatbot-db
#     engine: PG
#     version: "15"
#     size: basic-xs
#     num_nodes: 1
