# PRODUCTION-READY AI CHATBOT PLATFORM
# Optimized for Digital Ocean App Platform

name: aichatbot-platform
region: ams

# Production Alerts
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

# Global Environment Variables
envs:
- key: ENVIRONMENT
  scope: RUN_AND_BUILD_TIME
  value: production
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: postgresql://postgres.ompjkiiabyuegytncbwq:STEfanjohn!12@aws-0-eu-north-1.pooler.supabase.com:6543/postgres
- key: ADMIN_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: stefan@axiestudio.se
- key: ADMIN_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: STEfanjohn!12

# Platform Features
features:
- buildpack-stack=ubuntu-22

services:
  # AI CHATBOT BACKEND SERVICE
  - name: chatbot-backend
    environment_slug: python
    source_dir: /backend
    github:
      repo: axiestudio/aichatbot
      branch: main
      deploy_on_push: true

    # Production Build & Run Commands
    build_command: pip install --no-cache-dir -r requirements.txt
    run_command: python start.py

    # Production Instance Configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb

    # Network Configuration
    http_port: 8000

    # Production Health Check
    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Production Environment Variables
    envs:
      # Core Application Settings
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: LOG_LEVEL
        scope: RUN_AND_BUILD_TIME
        value: INFO
      - key: PYTHONUNBUFFERED
        scope: RUN_AND_BUILD_TIME
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        scope: RUN_AND_BUILD_TIME
        value: "1"

      # Security Configuration
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: prod-chatbot-secret-key-2024-digital-ocean-deployment-secure
      - key: JWT_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: prod-jwt-secret-key-2024-digital-ocean-chatbot-platform-secure

      # Admin Configuration
      - key: ADMIN_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: stefan@axiestudio.se
      - key: ADMIN_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: STEfanjohn!12

      # Database Configuration
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: postgresql://postgres.ompjkiiabyuegytncbwq:STEfanjohn!12@aws-0-eu-north-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: https://ompjkiiabyuegytncbwq.supabase.co
      - key: SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcGpraWlhYnl1ZWd5dG5jYndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDg2MjYsImV4cCI6MjA2ODQyNDYyNn0.z9j2pwMfKjfR9Fs__fHkzwj9fjgiNOUQZ5Z9zv5FD6Q

      # API Configuration
      - key: API_V1_STR
        scope: RUN_AND_BUILD_TIME
        value: /api/v1
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_AND_BUILD_TIME
        value: "30"

      # File Upload Configuration
      - key: MAX_FILE_SIZE
        scope: RUN_AND_BUILD_TIME
        value: "10485760"
      - key: UPLOAD_DIR
        scope: RUN_AND_BUILD_TIME
        value: ./uploads

      # Rate Limiting Configuration
      - key: RATE_LIMIT_REQUESTS
        scope: RUN_AND_BUILD_TIME
        value: "100"
      - key: RATE_LIMIT_WINDOW
        scope: RUN_AND_BUILD_TIME
        value: "60"

      # Production Optimizations
      - key: ENABLE_CACHING
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: CACHE_BACKEND
        scope: RUN_AND_BUILD_TIME
        value: supabase
      - key: CORS_ORIGINS
        scope: RUN_AND_BUILD_TIME
        value: "*"

# PRODUCTION DEPLOYMENT COMPLETE
# Frontend and database services can be added later when needed
# This configuration focuses on stable backend deployment first
