apiVersion: v1
kind: Namespace
metadata:
  name: chatbot-system
  labels:
    name: chatbot-system
    environment: production
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: chatbot-resource-quota
  namespace: chatbot-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: chatbot-limit-range
  namespace: chatbot-system
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
