apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: chatbot-system
  labels:
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  SECRET_KEY: <BASE64_ENCODED_SECRET_KEY>
  JWT_SECRET_KEY: <BASE64_ENCODED_JWT_SECRET_KEY>
  POSTGRES_PASSWORD: <BASE64_ENCODED_POSTGRES_PASSWORD>
  REDIS_PASSWORD: <BASE64_ENCODED_REDIS_PASSWORD>
  OPENAI_API_KEY: <BASE64_ENCODED_OPENAI_API_KEY>
  ANTHROPIC_API_KEY: <BASE64_ENCODED_ANTHROPIC_API_KEY>
  SUPABASE_ANON_KEY: <BASE64_ENCODED_SUPABASE_ANON_KEY>
  GRAFANA_PASSWORD: <BASE64_ENCODED_GRAFANA_PASSWORD>
  SENTRY_DSN: <BASE64_ENCODED_SENTRY_DSN>
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-tls
  namespace: chatbot-system
  labels:
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-registry
  namespace: chatbot-system
  labels:
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>
